<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_USINT_TO_BYTE" Id="{ef7b5d3d-1892-44e3-8b42-45254579f1b6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_USINT_TO_BYTE : BOOL
VAR_INPUT
	in : USINT;
	out : REFERENCE TO BYTE;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := USINT_TO_BYTE(in);
TryConvert_USINT_TO_BYTE := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>