<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_USINT_TO_ULINT" Id="{af11ee09-52bb-45c7-84de-6f5b88cbb8b1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_USINT_TO_ULINT : BOOL
VAR_INPUT
	in : USINT;
	out : REFERENCE TO ULINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := USINT_TO_ULINT(in);
TryConvert_USINT_TO_ULINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>