<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_USINT_TO_UINT" Id="{de67ea40-d943-4b67-9eb7-8bce1c1d2593}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_USINT_TO_UINT : BOOL
VAR_INPUT
	in : USINT;
	out : REFERENCE TO UINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := USINT_TO_UINT(in);
TryConvert_USINT_TO_UINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>