<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_USINT_TO_INT" Id="{14bd9e63-5212-488f-95f8-e5d655bec00a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_USINT_TO_INT : BOOL
VAR_INPUT
	in : USINT;
	out : REFERENCE TO INT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := USINT_TO_INT(in);
TryConvert_USINT_TO_INT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>