<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_USINT_TO_TOD" Id="{96587953-8bb4-42b1-b951-822ec9fa8919}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_USINT_TO_TOD : BOOL
VAR_INPUT
	in : USINT;
	out : REFERENCE TO TOD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := USINT_TO_TOD(in);
TryConvert_USINT_TO_TOD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>