<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DATE_TO_LINT" Id="{e3675d27-e698-4128-a2de-7cab697acdf4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_DATE_TO_LINT : BOOL
VAR_INPUT
	in : DATE;
	out : REFERENCE TO LINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := DATE_TO_LINT(in);
TryConvert_DATE_TO_LINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>