<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DATE_TO_BOOL" Id="{6e1b97d6-1554-4ebd-80cb-a27aeb287e41}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_DATE_TO_BOOL : BOOL
VAR_INPUT
	in : DATE;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := DATE_TO_BOOL(in);
TryConvert_DATE_TO_BOOL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>