<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MobjectConvertersUnitTests" Id="{1aed7e3f-196c-0ace-3f96-5e995ebe5325}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MobjectConvertersUnitTests
VAR
	eventEmitter_TestSuite : EventEmitter_TestSuite;
	eventEmitterInterface_TestSuite : EventEmitterInterface_TestSuite;
	eventTargetInterface_TestSuite : EventTargetInterface_TestSuite;
	eventHandlerInterface_TestSuite : EventHandlerInterface_TestSuite;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>