<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MobjectErrorsUnitTests" Id="{4237ec96-35e5-056b-2754-096569bdf2b1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MobjectErrorsUnitTests
VAR
	error_TestSuite : Error_TestSuite;
	nullError_TestSuite : NullError_TestSuite;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>