<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_ULINT_TO_REAL" Id="{7ac3a0e6-24e0-4c5d-a80b-6bd807f21b65}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_ULINT_TO_REAL : BOOL
VAR_INPUT
	in : ULINT;
	out : REFERENCE TO REAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := ULINT_TO_REAL(in);
TryConvert_ULINT_TO_REAL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>