<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_ULINT_TO_ULINT" Id="{490b83a2-d697-4a17-8d10-23f5b06ab6a4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_ULINT_TO_ULINT : BOOL
VAR_INPUT
	in : ULINT;
	out : REFERENCE TO ULINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;
TryConvert_ULINT_TO_ULINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>