<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_ULINT_TO_LREAL" Id="{7cc647d1-dfa5-4f4a-90de-b5a8717ccf69}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_ULINT_TO_LREAL : BOOL
VAR_INPUT
	in : ULINT;
	out : REFERENCE TO LREAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := ULINT_TO_LREAL(in);
TryConvert_ULINT_TO_LREAL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>