<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DT_TO_LREAL" Id="{ee4f6fb4-403b-4cf5-ba7a-fb21fb7c13dc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_DT_TO_LREAL : BOOL
VAR_INPUT
	in : DT;
	out : REFERENCE TO LREAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := DT_TO_LREAL(in);
TryConvert_DT_TO_LREAL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>