<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_SINT_TO_REAL" Id="{a4e297b2-c324-4029-9d8d-53da8a1b04e0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_SINT_TO_REAL : BOOL
VAR_INPUT
	in : SINT;
	out : REFERENCE TO REAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := SINT_TO_REAL(in);
TryConvert_SINT_TO_REAL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>