<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_UDINT_TO_DATE" Id="{e6581d9f-13d5-415a-b070-caea59c71a59}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_UDINT_TO_DATE : BOOL
VAR_INPUT
	in : UDINT;
	out : REFERENCE TO DATE;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := UDINT_TO_DATE(in);
TryConvert_UDINT_TO_DATE := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>