<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_UDINT_TO_DWORD" Id="{82836e95-0801-47e6-b55b-1c2e5f161caf}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_UDINT_TO_DWORD : BOOL
VAR_INPUT
	in : UDINT;
	out : REFERENCE TO DWORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := UDINT_TO_DWORD(in);
TryConvert_UDINT_TO_DWORD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>