<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_UINT_TO_LINT" Id="{dabd3f80-6053-4866-8986-2ce2b2462834}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_UINT_TO_LINT : BOOL
VAR_INPUT
	in : UINT;
	out : REFERENCE TO LINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := UINT_TO_LINT(in);
TryConvert_UINT_TO_LINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>