<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_UINT_TO_UDINT" Id="{d1916527-ccff-4b29-bdc7-952caa159eb9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_UINT_TO_UDINT : BOOL
VAR_INPUT
	in : UINT;
	out : REFERENCE TO UDINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := UINT_TO_UDINT(in);
TryConvert_UINT_TO_UDINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>