<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_UINT_TO_DATE" Id="{84909c88-ca23-4bbb-b33d-590ff562f02e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_UINT_TO_DATE : BOOL
VAR_INPUT
	in : UINT;
	out : REFERENCE TO DATE;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := UINT_TO_DATE(in);
TryConvert_UINT_TO_DATE := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>