<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_UINT_TO_UINT" Id="{b09eb73b-5781-46d5-b050-9231ac0896db}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_UINT_TO_UINT : BOOL
VAR_INPUT
	in : UINT;
	out : REFERENCE TO UINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;
TryConvert_UINT_TO_UINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>