<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_UINT_TO_TOD" Id="{3c768c42-81ac-40a7-8be2-0eb9a35d6e46}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_UINT_TO_TOD : BOOL
VAR_INPUT
	in : UINT;
	out : REFERENCE TO TOD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := UINT_TO_TOD(in);
TryConvert_UINT_TO_TOD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>