<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_UINT_TO_REAL" Id="{ea4044aa-17f6-41b2-9678-878c962d6360}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_UINT_TO_REAL : BOOL
VAR_INPUT
	in : UINT;
	out : REFERENCE TO REAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := UINT_TO_REAL(in);
TryConvert_UINT_TO_REAL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>