<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_UINT_TO_DWORD" Id="{6640dacd-c455-4d76-a33e-49c8f319e780}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_UINT_TO_DWORD : BOOL
VAR_INPUT
	in : UINT;
	out : REFERENCE TO DWORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := UINT_TO_DWORD(in);
TryConvert_UINT_TO_DWORD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>