<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_INT_TO_BOOL" Id="{d914834d-c802-4b5b-ac4c-38ad19b2b0a2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_INT_TO_BOOL : BOOL
VAR_INPUT
	in : INT;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := INT_TO_BOOL(in);
TryConvert_INT_TO_BOOL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>