<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DT_TO_BOOL" Id="{60c35869-7ac3-448d-b77f-d1f6d315ed64}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_DT_TO_BOOL : BOOL
VAR_INPUT
	in : DT;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := DT_TO_BOOL(in);
TryConvert_DT_TO_BOOL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>