<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DT_TO_DWORD" Id="{e384f971-a91d-4a5c-b793-e5c66dbd7de9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_DT_TO_DWORD : BOOL
VAR_INPUT
	in : DT;
	out : REFERENCE TO DWORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := DT_TO_DWORD(in);
TryConvert_DT_TO_DWORD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>