<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DWORD_TO_TIME" Id="{1b3562ac-e52c-4f56-a5b7-f5c430456bad}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_DWORD_TO_TIME : BOOL
VAR_INPUT
	in : DWORD;
	out : REFERENCE TO TIME;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := DWORD_TO_TIME(in);
TryConvert_DWORD_TO_TIME := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>