<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DWORD_TO_DATE" Id="{f99f9ca4-93cd-4aee-bb49-b32e35debdf3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_DWORD_TO_DATE : BOOL
VAR_INPUT
	in : DWORD;
	out : REFERENCE TO DATE;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := DWORD_TO_DATE(in);
TryConvert_DWORD_TO_DATE := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>