<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DWORD_TO_STRING" Id="{599da6d3-e45b-457a-b625-8ad8651b6752}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_DWORD_TO_STRING : BOOL
VAR_INPUT
	in : DWORD;
	out : REFERENCE TO STRING;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := DWORD_TO_STRING(in);
TryConvert_DWORD_TO_STRING := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>