<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DWORD_TO_LINT" Id="{2518adda-573f-4e12-bda5-8eb5c0f4fe49}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_DWORD_TO_LINT : BOOL
VAR_INPUT
	in : DWORD;
	out : REFERENCE TO LINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := DWORD_TO_LINT(in);
TryConvert_DWORD_TO_LINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>