<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MockEvent" Id="{92fe7472-59ce-063f-0ff1-2c7ed3de4a75}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK MockEvent IMPLEMENTS I_Event
VAR
	_name : T_MAXSTRING;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>