<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_ULINT_TO_LWORD" Id="{9fe744cc-6a16-4eb4-a565-0be1c5fd0df4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_ULINT_TO_LWORD : BOOL
VAR_INPUT
	in : ULINT;
	out : REFERENCE TO LWORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := ULINT_TO_LWORD(in);
TryConvert_ULINT_TO_LWORD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>