<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_TIME_TO_LINT" Id="{eebd0f30-4247-441d-a07c-112aea50813c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_TIME_TO_LINT : BOOL
VAR_INPUT
	in : TIME;
	out : REFERENCE TO LINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := TIME_TO_LINT(in);
TryConvert_TIME_TO_LINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>