<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_TIME_TO_DT" Id="{23d9c0bb-456c-430c-8e71-f2367bcc30f1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_TIME_TO_DT : BOOL
VAR_INPUT
	in : TIME;
	out : REFERENCE TO DT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := TIME_TO_DT(in);
TryConvert_TIME_TO_DT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>