<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_UINT_TO_STRING" Id="{1dc1e0d6-4596-4945-84e4-8c2fad31e6c3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_UINT_TO_STRING : BOOL
VAR_INPUT
	in : UINT;
	out : REFERENCE TO STRING;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := UINT_TO_STRING(in);
TryConvert_UINT_TO_STRING := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>