<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_UINT_TO_LWORD" Id="{18f6435d-ebb1-47c9-8f81-dac5692c64cd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_UINT_TO_LWORD : BOOL
VAR_INPUT
	in : UINT;
	out : REFERENCE TO LWORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := UINT_TO_LWORD(in);
TryConvert_UINT_TO_LWORD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>