<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_UINT_TO_DINT" Id="{b889ea89-3a4a-4a30-bd37-8fcc9d4d2c3c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_UINT_TO_DINT : BOOL
VAR_INPUT
	in : UINT;
	out : REFERENCE TO DINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := UINT_TO_DINT(in);
TryConvert_UINT_TO_DINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>