<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_INT_TO_LINT" Id="{93d9abf0-d80b-4659-a39a-ae33c7466bff}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_INT_TO_LINT : BOOL
VAR_INPUT
	in : INT;
	out : REFERENCE TO LINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := INT_TO_LINT(in);
TryConvert_INT_TO_LINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>