<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_INT_TO_STRING" Id="{09f0a8f7-9740-44c0-acb5-27352d951d97}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_INT_TO_STRING : BOOL
VAR_INPUT
	in : INT;
	out : REFERENCE TO STRING;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := INT_TO_STRING(in);
TryConvert_INT_TO_STRING := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>