<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_INT_TO_INT" Id="{fdca1b80-a104-4494-bdfe-37dc5f030b65}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_INT_TO_INT : BOOL
VAR_INPUT
	in : INT;
	out : REFERENCE TO INT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;
TryConvert_INT_TO_INT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>