<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_USINT_TO_USINT" Id="{fd97dc94-bcbf-40be-82c8-68b1f07ae791}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_USINT_TO_USINT : BOOL
VAR_INPUT
	in : USINT;
	out : REFERENCE TO USINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;
TryConvert_USINT_TO_USINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>