<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_USINT_TO_REAL" Id="{149b1225-62c5-4056-b2c6-a452e4b08e8c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_USINT_TO_REAL : BOOL
VAR_INPUT
	in : USINT;
	out : REFERENCE TO REAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := USINT_TO_REAL(in);
TryConvert_USINT_TO_REAL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>