<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_USINT_TO_TIME" Id="{f176bf1d-5816-40ca-afb3-424aeeff9b69}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_USINT_TO_TIME : BOOL
VAR_INPUT
	in : USINT;
	out : REFERENCE TO TIME;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := USINT_TO_TIME(in);
TryConvert_USINT_TO_TIME := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>