<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_USINT_TO_LINT" Id="{54f04683-ec08-48f1-8192-b2a1124bc132}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_USINT_TO_LINT : BOOL
VAR_INPUT
	in : USINT;
	out : REFERENCE TO LINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := USINT_TO_LINT(in);
TryConvert_USINT_TO_LINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>