<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_USINT_TO_LREAL" Id="{1987ac12-7eab-4884-8971-2f5651d0794f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_USINT_TO_LREAL : BOOL
VAR_INPUT
	in : USINT;
	out : REFERENCE TO LREAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := USINT_TO_LREAL(in);
TryConvert_USINT_TO_LREAL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>