<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BOOL_TO_LREAL" Id="{c0cdfe97-538c-4556-880c-b38594c10d94}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BOOL_TO_LREAL : BOOL
VAR_INPUT
	in : BOOL;
	out : REFERENCE TO LREAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BOOL_TO_LREAL(in);
TryConvert_BOOL_TO_LREAL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>