<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BOOL_TO_TIME" Id="{70a79800-97a1-448f-ba0d-0737734a8af9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BOOL_TO_TIME : BOOL
VAR_INPUT
	in : BOOL;
	out : REFERENCE TO TIME;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BOOL_TO_TIME(in);
TryConvert_BOOL_TO_TIME := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>