<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BOOL_TO_STRING" Id="{8096e369-4428-4d4c-b536-ff4218bfa109}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BOOL_TO_STRING : BOOL
VAR_INPUT
	in : BOOL;
	out : REFERENCE TO STRING;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BOOL_TO_STRING(in);
TryConvert_BOOL_TO_STRING := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>