<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BOOL_TO_SINT" Id="{8aa40036-d05a-4892-980b-43966271f9ed}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BOOL_TO_SINT : BOOL
VAR_INPUT
	in : BOOL;
	out : REFERENCE TO SINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BOOL_TO_SINT(in);
TryConvert_BOOL_TO_SINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>