<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BOOL_TO_DT" Id="{4696d843-7a22-457a-99b9-c40bd96f9f78}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BOOL_TO_DT : BOOL
VAR_INPUT
	in : BOOL;
	out : REFERENCE TO DT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BOOL_TO_DT(in);
TryConvert_BOOL_TO_DT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>