<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BYTE_TO_WORD" Id="{6c755a7a-fb87-461e-9a90-857f9cdaaa7a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BYTE_TO_WORD : BOOL
VAR_INPUT
	in : BYTE;
	out : REFERENCE TO WORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BYTE_TO_WORD(in);
TryConvert_BYTE_TO_WORD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>