<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BYTE_TO_ULINT" Id="{4ea4ad62-e815-4194-92cb-e0764d4d5716}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BYTE_TO_ULINT : BOOL
VAR_INPUT
	in : BYTE;
	out : REFERENCE TO ULINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BYTE_TO_ULINT(in);
TryConvert_BYTE_TO_ULINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>