<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BYTE_TO_DINT" Id="{0c673b06-1ee9-458f-a518-0af935611b69}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BYTE_TO_DINT : BOOL
VAR_INPUT
	in : BYTE;
	out : REFERENCE TO DINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BYTE_TO_DINT(in);
TryConvert_BYTE_TO_DINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>