<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_LWORD_TO_ULINT" Id="{12d55139-a6c8-4b3c-bc39-269aaf20ee4e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_LWORD_TO_ULINT : BOOL
VAR_INPUT
	in : LWORD;
	out : REFERENCE TO ULINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := LWORD_TO_ULINT(in);
TryConvert_LWORD_TO_ULINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>