<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.13">
  <POU Name="RejectWithMessageSyncHandler" Id="{f7dd51c4-b7b4-0b91-25e7-17b220c50da2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK RejectWithMessageSyncHandler IMPLEMENTS I_SynchronousRpcHandler
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Handle" Id="{cc098160-fa6a-0eca-2338-0c59c1006001}">
      <Declaration><![CDATA[METHOD Handle
VAR_INPUT
	Parameters : I_Deserializer;
	Response : I_SynchronousRpcResponse;
END_VAR
VAR
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[Response.RejectWithError('EXAMPLE_ERROR_CODE','This is the reject message');]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>