<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.13">
  <POU Name="RejectWithMessageAsyncHandler" Id="{cb9503fc-4aa7-0763-24ec-bc44822dcf7e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK RejectWithMessageAsyncHandler IMPLEMENTS I_AsynchronousRpcHandler
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Handle" Id="{d1acf3c1-eeda-048f-1f5a-1add869c4d30}">
      <Declaration><![CDATA[METHOD Handle
VAR_INPUT
	Parameters : I_Deserializer;
	Response : I_AsynchronousRpcResponse;
END_VAR
VAR
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[Response.RejectWithError('EXAMPLE_ERROR_CODE','This is the reject message');]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>