<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_WORD_TO_REAL" Id="{e412c9a1-09e9-42c7-9a18-911a2bbd73df}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_WORD_TO_REAL : BOOL
VAR_INPUT
	in : WORD;
	out : REFERENCE TO REAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := WORD_TO_REAL(in);
TryConvert_WORD_TO_REAL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>