<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_WORD_TO_ULINT" Id="{32910ef4-b99d-4453-a52d-2d4cfc45e52b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_WORD_TO_ULINT : BOOL
VAR_INPUT
	in : WORD;
	out : REFERENCE TO ULINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := WORD_TO_ULINT(in);
TryConvert_WORD_TO_ULINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>