<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_WORD_TO_DT" Id="{6df3fc83-4a7d-4ad4-bf1c-6be2c737e414}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_WORD_TO_DT : BOOL
VAR_INPUT
	in : WORD;
	out : REFERENCE TO DT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := WORD_TO_DT(in);
TryConvert_WORD_TO_DT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>