<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_WORD_TO_LWORD" Id="{eb1771e1-c22f-43f7-98fd-ca3890978568}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_WORD_TO_LWORD : BOOL
VAR_INPUT
	in : WORD;
	out : REFERENCE TO LWORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := WORD_TO_LWORD(in);
TryConvert_WORD_TO_LWORD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>