<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_WORD_TO_LINT" Id="{cf4f9759-95cb-45ce-b432-65893f39f7e6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_WORD_TO_LINT : BOOL
VAR_INPUT
	in : WORD;
	out : REFERENCE TO LINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := WORD_TO_LINT(in);
TryConvert_WORD_TO_LINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>