<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_SINT_TO_INT" Id="{5681fc5f-cc0b-4cd6-8360-598f78ed34e7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_SINT_TO_INT : BOOL
VAR_INPUT
	in : SINT;
	out : REFERENCE TO INT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := SINT_TO_INT(in);
TryConvert_SINT_TO_INT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>