<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_SINT_TO_LREAL" Id="{f8a8bc74-6071-4b3d-a1a3-c7510bd200c1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_SINT_TO_LREAL : BOOL
VAR_INPUT
	in : SINT;
	out : REFERENCE TO LREAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := SINT_TO_LREAL(in);
TryConvert_SINT_TO_LREAL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>