<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BOOL_TO_UINT" Id="{557b4e01-4285-4386-a7b1-e95a2dbb12ab}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BOOL_TO_UINT : BOOL
VAR_INPUT
	in : BOOL;
	out : REFERENCE TO UINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BOOL_TO_UINT(in);
TryConvert_BOOL_TO_UINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>