<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BOOL_TO_DATE" Id="{fa02b83b-207c-4a3e-88f7-c579ded2bd2a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BOOL_TO_DATE : BOOL
VAR_INPUT
	in : BOOL;
	out : REFERENCE TO DATE;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BOOL_TO_DATE(in);
TryConvert_BOOL_TO_DATE := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>