<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BOOL_TO_LINT" Id="{66cc816e-6c35-49eb-9c2c-8d3b055ccd0f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BOOL_TO_LINT : BOOL
VAR_INPUT
	in : BOOL;
	out : REFERENCE TO LINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BOOL_TO_LINT(in);
TryConvert_BOOL_TO_LINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>