<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BOOL_TO_REAL" Id="{232ac03b-0978-47a2-ba43-0ffa0eb32647}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BOOL_TO_REAL : BOOL
VAR_INPUT
	in : BOOL;
	out : REFERENCE TO REAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BOOL_TO_REAL(in);
TryConvert_BOOL_TO_REAL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>