<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DINT_TO_DINT" Id="{f1341758-4031-4b62-8c89-b756794f57db}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_DINT_TO_DINT : BOOL
VAR_INPUT
	in : DINT;
	out : REFERENCE TO DINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;
TryConvert_DINT_TO_DINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>