<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_TIME_TO_BOOL" Id="{06bef351-24ee-4530-bdf3-fc459702e129}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_TIME_TO_BOOL : BOOL
VAR_INPUT
	in : TIME;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := TIME_TO_BOOL(in);
TryConvert_TIME_TO_BOOL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>