<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_TIME_TO_UDINT" Id="{9bc4082a-5da9-456f-bfe8-d135b6f17c2b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_TIME_TO_UDINT : BOOL
VAR_INPUT
	in : TIME;
	out : REFERENCE TO UDINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := TIME_TO_UDINT(in);
TryConvert_TIME_TO_UDINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>