<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_TIME_TO_STRING" Id="{64131d16-9a5e-4134-b8ac-ae06f8dc9043}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_TIME_TO_STRING : BOOL
VAR_INPUT
	in : TIME;
	out : REFERENCE TO STRING;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := TIME_TO_STRING(in);
TryConvert_TIME_TO_STRING := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>