<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_TOD_TO_LREAL" Id="{6c049ce6-df49-4217-933d-a7a54ee70bcf}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_TOD_TO_LREAL : BOOL
VAR_INPUT
	in : TOD;
	out : REFERENCE TO LREAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := TOD_TO_LREAL(in);
TryConvert_TOD_TO_LREAL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>