<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_TOD_TO_DATE" Id="{abb1d056-0113-45da-897a-950b7b46f0d4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_TOD_TO_DATE : BOOL
VAR_INPUT
	in : TOD;
	out : REFERENCE TO DATE;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := TOD_TO_DATE(in);
TryConvert_TOD_TO_DATE := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>