<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_TOD_TO_TOD" Id="{267b702b-d8ee-4721-bd01-82131ae2024e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_TOD_TO_TOD : BOOL
VAR_INPUT
	in : TOD;
	out : REFERENCE TO TOD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;
TryConvert_TOD_TO_TOD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>