<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_TOD_TO_UDINT" Id="{267fdafd-19ea-413b-9cd4-97f6a319d229}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_TOD_TO_UDINT : BOOL
VAR_INPUT
	in : TOD;
	out : REFERENCE TO UDINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := TOD_TO_UDINT(in);
TryConvert_TOD_TO_UDINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>