<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_TOD_TO_ULINT" Id="{4aa70864-7320-4c09-b5a4-bc0d9914bc3a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_TOD_TO_ULINT : BOOL
VAR_INPUT
	in : TOD;
	out : REFERENCE TO ULINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := TOD_TO_ULINT(in);
TryConvert_TOD_TO_ULINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>