<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DATE_TO_DWORD" Id="{569bc39d-87c1-4826-975d-a6da38752bb4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_DATE_TO_DWORD : BOOL
VAR_INPUT
	in : DATE;
	out : REFERENCE TO DWORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := DATE_TO_DWORD(in);
TryConvert_DATE_TO_DWORD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>