<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BYTE_TO_DT" Id="{2d22efe0-acdb-44f3-b236-e47cd1637a20}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BYTE_TO_DT : BOOL
VAR_INPUT
	in : BYTE;
	out : REFERENCE TO DT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BYTE_TO_DT(in);
TryConvert_BYTE_TO_DT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>