<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BYTE_TO_LWORD" Id="{b0a886c9-e493-4bf7-8667-42e42fa6ea4f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BYTE_TO_LWORD : BOOL
VAR_INPUT
	in : BYTE;
	out : REFERENCE TO LWORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BYTE_TO_LWORD(in);
TryConvert_BYTE_TO_LWORD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>