<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_BYTE_TO_UINT" Id="{31707e17-238e-4094-a545-b0fe15df55d7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_BYTE_TO_UINT : BOOL
VAR_INPUT
	in : BYTE;
	out : REFERENCE TO UINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := BYTE_TO_UINT(in);
TryConvert_BYTE_TO_UINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>