<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_LWORD_TO_STRING" Id="{1634f022-e36f-4266-be18-6ae305f7ee6f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_LWORD_TO_STRING : BOOL
VAR_INPUT
	in : LWORD;
	out : REFERENCE TO STRING;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := LWORD_TO_STRING(in);
TryConvert_LWORD_TO_STRING := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>