<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_STRING_TO_BOOL" Id="{8faa92b9-f319-459d-b0b1-345b0b2493f1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_STRING_TO_BOOL : BOOL
VAR_INPUT
	in : STRING;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := STRING_TO_BOOL(in);
TryConvert_STRING_TO_BOOL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>