<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_WORD_TO_DINT" Id="{fed80a6b-49f3-4969-ad0f-8137d32cf122}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_WORD_TO_DINT : BOOL
VAR_INPUT
	in : WORD;
	out : REFERENCE TO DINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := WORD_TO_DINT(in);
TryConvert_WORD_TO_DINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>