<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_WORD_TO_DATE" Id="{64311c76-612e-46e7-b52b-c0225bfc05f3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_WORD_TO_DATE : BOOL
VAR_INPUT
	in : WORD;
	out : REFERENCE TO DATE;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := WORD_TO_DATE(in);
TryConvert_WORD_TO_DATE := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>