<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_WORD_TO_TOD" Id="{18146614-db52-48b2-86a3-ff503a4f0188}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_WORD_TO_TOD : BOOL
VAR_INPUT
	in : WORD;
	out : REFERENCE TO TOD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := WORD_TO_TOD(in);
TryConvert_WORD_TO_TOD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>