<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_WORD_TO_WORD" Id="{1c15fe9b-bb48-4a61-928a-d7d0d8ffdf04}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_WORD_TO_WORD : BOOL
VAR_INPUT
	in : WORD;
	out : REFERENCE TO WORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;
TryConvert_WORD_TO_WORD := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>