<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_UDINT_TO_DT" Id="{171d014c-8458-4f5f-9543-75c0ba493817}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_UDINT_TO_DT : BOOL
VAR_INPUT
	in : UDINT;
	out : REFERENCE TO DT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := UDINT_TO_DT(in);
TryConvert_UDINT_TO_DT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>