<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_UDINT_TO_ULINT" Id="{fc061c09-771b-4f24-a185-19209d9b1152}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_UDINT_TO_ULINT : BOOL
VAR_INPUT
	in : UDINT;
	out : REFERENCE TO ULINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := UDINT_TO_ULINT(in);
TryConvert_UDINT_TO_ULINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>