<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="KeyValueCollectionDisposedEvent" Id="{c3256d31-7525-07f1-1bfc-98bb30dc134d}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'} 
{attribute 'no_explicit_call' := 'This FB is a CLASS and must be accessed using methods or properties'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK KeyValueCollectionDisposedEvent EXTENDS KeyValueCollectionEvent IMPLEMENTS I_KeyValueCollectionDisposedEvent]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>