<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DWORD_TO_UDINT" Id="{a4470018-2e4f-46ad-bd39-fa509b0c94ad}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_DWORD_TO_UDINT : BOOL
VAR_INPUT
	in : DWORD;
	out : REFERENCE TO UDINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := DWORD_TO_UDINT(in);
TryConvert_DWORD_TO_UDINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>