<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_DINT_TO_STRING" Id="{0c4755b4-b919-4542-99f6-5e89fbe55a4b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_DINT_TO_STRING : BOOL
VAR_INPUT
	in : DINT;
	out : REFERENCE TO STRING;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := DINT_TO_STRING(in);
TryConvert_DINT_TO_STRING := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>