<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_LINT_TO_LREAL" Id="{231e04d5-6689-4396-b658-2095aa2da739}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_LINT_TO_LREAL : BOOL
VAR_INPUT
	in : LINT;
	out : REFERENCE TO LREAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := LINT_TO_LREAL(in);
TryConvert_LINT_TO_LREAL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>