<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_TOD_TO_REAL" Id="{734e7d22-ea80-4c8e-a660-edfd05194a62}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_TOD_TO_REAL : BOOL
VAR_INPUT
	in : TOD;
	out : REFERENCE TO REAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := TOD_TO_REAL(in);
TryConvert_TOD_TO_REAL := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>