<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TryConvert_TOD_TO_LINT" Id="{408e4764-8317-41cd-9838-88c8a845681b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TryConvert_TOD_TO_LINT : BOOL
VAR_INPUT
	in : TOD;
	out : REFERENCE TO LINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := TOD_TO_LINT(in);
TryConvert_TOD_TO_LINT := TRUE;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>