<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MobjectDisposableUnitTests" Id="{16004530-efeb-0415-1922-33cae33576f7}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MobjectDisposableUnitTests
VAR
	disposable_TestSuite : Disposable_TestSuite;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>